version: '3.7'

services:

  front:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  postgres-trackly-bd:
    image: postgres:13-alpine
    container_name: postgres-trackly-bd
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my-network
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server --console-address ":9001" /data
    networks:
      - my-network
  #   Сервис для вашего Go-приложения
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres-trackly-bd
      - minio

    ports:
      - "8080:8080"
    networks:
      - my-network
    env_file:
      - .env

# Настройка volumes и networks
networks:
  my-network:
    driver: bridge