port: 8080
jwt_secret: best-secret-in-the-world

database:
  host: postgres-trackly-bd
  port: 5432
  username: postgres
  password: postgres
  dbname: trackly-db

minio:
  endpoint: minio:9000
  bucket_name: best-bucket
  root_user: root
  root_password: best-password
  use_ssl: false
